# Data Manipulation

In [30]:
import torch

## Create Tensor

Create a new Tensor

In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5414e-43, 1.6255e-43]])


Initialize a new Tensor

In [9]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2308, 0.8696, 0.7746],
        [0.4813, 0.9786, 0.2588],
        [0.8676, 0.9103, 0.5296],
        [0.2926, 0.7509, 0.8306],
        [0.3960, 0.7168, 0.7647]])


Create a Tensor with zeros

In [10]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Create a Tensor from data

In [11]:
x = torch.tensor([5.5000, 3])
print(x)

tensor([5.5000, 3.0000])


Create a Tensor alike

In [13]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6344, -0.0918, -0.4435],
        [ 0.2291, -0.3344,  0.5697],
        [-0.2075,  1.9524,  0.3097],
        [-0.1789, -0.2169, -1.5061],
        [ 1.4506,  0.4668, -0.9015]])


shape and size()

In [14]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


## Operations

### Arithmetic

In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.4928,  0.1476,  0.3760],
        [ 0.6454,  0.4545,  0.7825],
        [ 0.3937,  2.8987,  0.5235],
        [ 0.6029,  0.3083, -1.1013],
        [ 2.2031,  0.8505,  0.0971]])


In [17]:
print(torch.add(x, y))

tensor([[-0.4928,  0.1476,  0.3760],
        [ 0.6454,  0.4545,  0.7825],
        [ 0.3937,  2.8987,  0.5235],
        [ 0.6029,  0.3083, -1.1013],
        [ 2.2031,  0.8505,  0.0971]])


Given the output

In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4928,  0.1476,  0.3760],
        [ 0.6454,  0.4545,  0.7825],
        [ 0.3937,  2.8987,  0.5235],
        [ 0.6029,  0.3083, -1.1013],
        [ 2.2031,  0.8505,  0.0971]])


Inplace

In [20]:
y.add_(x)
print(y)

#inplace operations always have "_", x.copy_(y), x.t_()

tensor([[-1.1272,  0.0558, -0.0675],
        [ 0.8745,  0.1201,  1.3523],
        [ 0.1862,  4.8511,  0.8332],
        [ 0.4241,  0.0914, -2.6074],
        [ 3.6536,  1.3173, -0.8043]])


### Indexing and Slicing

The referenced source data through indexing or slicing will also be modified.

In [21]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([0.3656, 0.9082, 0.5565])
tensor([0.3656, 0.9082, 0.5565])


There are other functions for indexing and slicing:

index_select(input, dim, index)

masked_select(input, mask)

non_zero(input)

gather(input, dim, index)

### Shape

In [24]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[ 0.3656,  0.9082,  0.5565],
        [ 0.2291, -0.3344,  0.5697],
        [-0.2075,  1.9524,  0.3097],
        [-0.1789, -0.2169, -1.5061],
        [ 1.4506,  0.4668, -0.9015]])
tensor([ 0.3656,  0.9082,  0.5565,  0.2291, -0.3344,  0.5697, -0.2075,  1.9524,
         0.3097, -0.1789, -0.2169, -1.5061,  1.4506,  0.4668, -0.9015])
tensor([[ 0.3656,  0.9082,  0.5565,  0.2291, -0.3344],
        [ 0.5697, -0.2075,  1.9524,  0.3097, -0.1789],
        [-0.2169, -1.5061,  1.4506,  0.4668, -0.9015]])


x, y, z share the same source data.

In [25]:
x += 1
print(x)
print(y)

tensor([[ 1.3656,  1.9082,  1.5565],
        [ 1.2291,  0.6656,  1.5697],
        [ 0.7925,  2.9524,  1.3097],
        [ 0.8211,  0.7831, -0.5061],
        [ 2.4506,  1.4668,  0.0985]])
tensor([ 1.3656,  1.9082,  1.5565,  1.2291,  0.6656,  1.5697,  0.7925,  2.9524,
         1.3097,  0.8211,  0.7831, -0.5061,  2.4506,  1.4668,  0.0985])


If we want a real reshaped copy of it

In [26]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 0.3656,  0.9082,  0.5565],
        [ 0.2291, -0.3344,  0.5697],
        [-0.2075,  1.9524,  0.3097],
        [-0.1789, -0.2169, -1.5061],
        [ 1.4506,  0.4668, -0.9015]])
tensor([ 1.3656,  1.9082,  1.5565,  1.2291,  0.6656,  1.5697,  0.7925,  2.9524,
         1.3097,  0.8211,  0.7831, -0.5061,  2.4506,  1.4668,  0.0985])


Convert a scale to python number

In [29]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.7212])
0.7212088108062744


There are other functions

trace	

diag	

triu/tril	

mm/bmm	

addmm/addbmm/addmv/addr/badbmm

t

dot/cross

inverse

svd

## Broadcasting

In [37]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## Saving Memory

In [38]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


Use indexing to save memory

In [39]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


Some other ways

In [40]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


## Mutal Transformation of NDArray and Numpy

Note! They are the same data

### Tensor to Numpy

In [42]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [ 1.  1.  1.  1.  1.]
tensor([2., 2., 2., 2., 2.]) [ 2.  2.  2.  2.  2.]
tensor([3., 3., 3., 3., 3.]) [ 3.  3.  3.  3.  3.]


### Numpy to Tensor

In [43]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[ 1.  1.  1.  1.  1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[ 2.  2.  2.  2.  2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[ 3.  3.  3.  3.  3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### Numpy to Tensor (Copy)

Use torch.tensor to convert Numpy to Tensor. It does not share the data.

In [45]:
c = torch.tensor(a)
a += 1
print(a, c)

[ 5.  5.  5.  5.  5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


## Tensor on GPU

In [47]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))