# Automatic Differentiation

In [3]:
import torch
from torch.autograd import Variable
print(torch.__version__)

1.2.0


## A Simple Example

$y = 2\mathbf{x}^{\top}\mathbf{x}$

In [4]:
x = Variable(torch.arange(4, dtype=torch.float32).reshape((4, 1)), requires_grad=True)
print(x)

tensor([[0.],
        [1.],
        [2.],
        [3.]], requires_grad=True)


In [5]:
y = 2*torch.mm(x.t(), x)
print(y)

tensor([[28.]], grad_fn=<MulBackward0>)


In [6]:
y.backward()

In [8]:
print("x.grad", x.grad)
print("x.grad_fn", x.grad_fn)
print("y.grad_fn", y.grad_fn)

x.grad tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])
x.grad_fn None
y.grad_fn <MulBackward0 object at 0x11cf537b8>


In [10]:
x.grad - 4*x
print((x.grad - 4*x).norm().item() == 0)
print(x.grad)

True
tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])


## Computing the Gradient of Python Control Flow

In [29]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [33]:
a = torch.randn(size=(1, ))
a.requires_grad=True
d = f(a)
d.backward()
print(a.grad)
print(d / a)

tensor([2048.])
tensor([2048.], grad_fn=<DivBackward0>)
